package com.pshop.station.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Coleccion generated by hbm2java
 */
public class Coleccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6510907094497582463L;
	private int id;
	private int estatus;
	private String nombre;
	private Date fechaUmodif;
	private int idUsuarioUmodif;
	private String nombreMostrar;
	private Integer ranking;
	private String portadaUrl;
	private String usuario;

	public Coleccion() {
	}

	public Coleccion(int id, int estatus, String nombre, Date fechaUmodif, int idUsuarioUmodif, String portadaUrl) {
		this.id = id;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.idUsuarioUmodif = idUsuarioUmodif;
		this.portadaUrl = portadaUrl;
	}

	public Coleccion(int id, int estatus, String nombre, Date fechaUmodif, int idUsuarioUmodif, String nombreMostrar,
			Integer ranking, String portadaUrl) {
		this.id = id;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.idUsuarioUmodif = idUsuarioUmodif;
		this.nombreMostrar = nombreMostrar;
		this.ranking = ranking;
		this.portadaUrl = portadaUrl;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public int getIdUsuarioUmodif() {
		return this.idUsuarioUmodif;
	}

	public void setIdUsuarioUmodif(int idUsuarioUmodif) {
		this.idUsuarioUmodif = idUsuarioUmodif;
	}

	public String getNombreMostrar() {
		return this.nombreMostrar;
	}

	public void setNombreMostrar(String nombreMostrar) {
		this.nombreMostrar = nombreMostrar;
	}

	public Integer getRanking() {
		return this.ranking;
	}

	public void setRanking(Integer ranking) {
		this.ranking = ranking;
	}

	public String getPortadaUrl() {
		return portadaUrl;
	}

	public void setPortadaUrl(String portadaUrl) {
		this.portadaUrl = portadaUrl;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Override
	public String toString() {
		return "Coleccion [id=" + id + ", estatus=" + estatus + ", nombre=" + nombre + ", fechaUmodif=" + fechaUmodif
				+ ", idUsuarioUmodif=" + idUsuarioUmodif + ", nombreMostrar=" + nombreMostrar + ", ranking=" + ranking
				+ ", portadaUrl=" + portadaUrl + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + estatus;
		result = prime * result + ((fechaUmodif == null) ? 0 : fechaUmodif.hashCode());
		result = prime * result + id;
		result = prime * result + idUsuarioUmodif;
		result = prime * result + ((nombre == null) ? 0 : nombre.hashCode());
		result = prime * result + ((nombreMostrar == null) ? 0 : nombreMostrar.hashCode());
		result = prime * result + ((portadaUrl == null) ? 0 : portadaUrl.hashCode());
		result = prime * result + ((ranking == null) ? 0 : ranking.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Coleccion other = (Coleccion) obj;
		if (estatus != other.estatus)
			return false;
		if (fechaUmodif == null) {
			if (other.fechaUmodif != null)
				return false;
		} else if (!fechaUmodif.equals(other.fechaUmodif))
			return false;
		if (id != other.id)
			return false;
		if (idUsuarioUmodif != other.idUsuarioUmodif)
			return false;
		if (nombre == null) {
			if (other.nombre != null)
				return false;
		} else if (!nombre.equals(other.nombre))
			return false;
		if (nombreMostrar == null) {
			if (other.nombreMostrar != null)
				return false;
		} else if (!nombreMostrar.equals(other.nombreMostrar))
			return false;
		if (portadaUrl == null) {
			if (other.portadaUrl != null)
				return false;
		} else if (!portadaUrl.equals(other.portadaUrl))
			return false;
		if (ranking == null) {
			if (other.ranking != null)
				return false;
		} else if (!ranking.equals(other.ranking))
			return false;
		return true;
	}
	
}
