package com.pshop.station.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

/**
 * CompraId generated by hbm2java
 */
public class CompraId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7227843486673662935L;
	private int idUsuario;
	private int idPublicacion;

	public CompraId() {
	}

	public CompraId(int idUsuario, int idPublicacion) {
		this.idUsuario = idUsuario;
		this.idPublicacion = idPublicacion;
	}

	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdPublicacion() {
		return this.idPublicacion;
	}

	public void setIdPublicacion(int idPublicacion) {
		this.idPublicacion = idPublicacion;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idPublicacion;
		result = prime * result + idUsuario;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CompraId other = (CompraId) obj;
		if (idPublicacion != other.idPublicacion)
			return false;
		if (idUsuario != other.idUsuario)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "CompraId [idUsuario=" + idUsuario + ", idPublicacion=" + idPublicacion + "]";
	}

}
