package com.pshop.station.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Editorial generated by hbm2java
 */
public class Editorial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6230582954217273978L;
	private int id;
	private String email;
	private int estatus;
	private String nombre;
	private String rfc;
	private String telefono;
	private Date fechaUmodif;
	private int idUsuarioUmodif;
	private String usuario;

	public Editorial() {
	}

	public Editorial(int id, int estatus, String nombre, Date fechaUmodif, int idUsuarioUmodif) {
		this.id = id;
		this.estatus = estatus;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
		this.idUsuarioUmodif = idUsuarioUmodif;
	}

	public Editorial(int id, String email, int estatus, String nombre, String rfc, String telefono, Date fechaUmodif,
			int idUsuarioUmodif) {
		this.id = id;
		this.email = email;
		this.estatus = estatus;
		this.nombre = nombre;
		this.rfc = rfc;
		this.telefono = telefono;
		this.fechaUmodif = fechaUmodif;
		this.idUsuarioUmodif = idUsuarioUmodif;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public int getIdUsuarioUmodif() {
		return this.idUsuarioUmodif;
	}

	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public void setIdUsuarioUmodif(int idUsuarioUmodif) {
		this.idUsuarioUmodif = idUsuarioUmodif;
	}

	@Override
	public String toString() {
		return "Editorial [id=" + id + ", email=" + email + ", estatus=" + estatus + ", nombre=" + nombre + ", rfc="
				+ rfc + ", telefono=" + telefono + ", fechaUmodif=" + fechaUmodif + ", idUsuarioUmodif="
				+ idUsuarioUmodif + "]";
	}

	
}
