package com.pshop.station.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5614807830519670366L;
	private Integer id;
	private String descripcion;
	private String nombre;
	private Date fechaUmodif;

	public Perfil() {
	}

	public Perfil(String nombre, Date fechaUmodif) {
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public Perfil(String descripcion, String nombre, Date fechaUmodif) {
		this.descripcion = descripcion;
		this.nombre = nombre;
		this.fechaUmodif = fechaUmodif;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	@Override
	public String toString() {
		return "Perfil [id=" + id + ", descripcion=" + descripcion + ", nombre=" + nombre + ", fechaUmodif="
				+ fechaUmodif + "]";
	}

}
