package com.pshop.station.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

/**
 * Properties generated by hbm2java
 */
public class Properties implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 389091386703274000L;
	private int id;
	private String key;
	private String value;

	public Properties() {
	}

	public Properties(int id) {
		this.id = id;
	}

	public Properties(int id, String key, String value) {
		this.id = id;
		this.key = key;
		this.value = value;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public String toString() {
		return "Properties [id=" + id + ", key=" + key + ", value=" + value + "]";
	}

}
