package com.pshop.station.persistence.pojo;
// Generated 02-jun-2016 21:47:36 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;

/**
 * Publicacion generated by hbm2java
 */
public class Publicacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7576625373651137083L;
	private int id;
	private BigDecimal descuento;
	private int estatus;
	private String isbn;
	private String nombre;
	private Short numeroPaginas;
	private byte[] portada;
	private BigDecimal precio;
	private String resumen;
	private String urlArchivo;
	private Date fechaUmodif;
	private int idUsuarioUmodif;
	private String portadaUrl;
	private Coleccion coleccion;
	private Usuario usuario;
	private Fuente fuente;
	private Editorial editorial;
	private Date fechaCompraTemporal;
	private boolean comprada;
	private String usuarioMail;

	public Publicacion() {
	}

	public Publicacion(int id, int estatus, String isbn, String nombre, String urlArchivo, Date fechaUmodif,
		int idUsuarioUmodif, Coleccion coleccion, Usuario usuario, Fuente fuente, Editorial editorial, String portadaUrl) {
		this.id = id;
		this.estatus = estatus;
		this.isbn = isbn;
		this.nombre = nombre;
		this.urlArchivo = urlArchivo;
		this.fechaUmodif = fechaUmodif;
		this.idUsuarioUmodif = idUsuarioUmodif;
		this.coleccion = coleccion;
		this.usuario = usuario;
		this.fuente = fuente;
		this.editorial = editorial;
		this.portadaUrl = portadaUrl;
	}

	public Publicacion(int id, BigDecimal descuento, int estatus, String isbn, String nombre,
			Short numeroPaginas, byte[] portada, BigDecimal precio, String resumen, String urlArchivo, Date fechaUmodif,
			int idUsuarioUmodif, Coleccion coleccion, Usuario usuario, Fuente fuente, Editorial editorial, String portadaUrl) {
		this.id = id;
		this.descuento = descuento;
		this.estatus = estatus;
		this.isbn = isbn;
		this.nombre = nombre;
		this.numeroPaginas = numeroPaginas;
		this.portada = portada;
		this.precio = precio;
		this.resumen = resumen;
		this.urlArchivo = urlArchivo;
		this.fechaUmodif = fechaUmodif;
		this.idUsuarioUmodif = idUsuarioUmodif;
		this.coleccion = coleccion;
		this.usuario = usuario;
		this.fuente = fuente;
		this.editorial = editorial;
		this.portadaUrl = portadaUrl;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public BigDecimal getDescuento() {
		return this.descuento;
	}

	public void setDescuento(BigDecimal descuento) {
		this.descuento = descuento;
	}

	public int getEstatus() {
		return this.estatus;
	}

	public void setEstatus(int estatus) {
		this.estatus = estatus;
	}

	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Short getNumeroPaginas() {
		return this.numeroPaginas;
	}

	public void setNumeroPaginas(Short numeroPaginas) {
		this.numeroPaginas = numeroPaginas;
	}

	public byte[] getPortada() {
		return this.portada;
	}

	public void setPortada(byte[] portada) {
		this.portada = portada;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public String getResumen() {
		return this.resumen;
	}

	public void setResumen(String resumen) {
		this.resumen = resumen;
	}

	public String getUrlArchivo() {
		return this.urlArchivo;
	}

	public void setUrlArchivo(String urlArchivo) {
		this.urlArchivo = urlArchivo;
	}

	public Date getFechaUmodif() {
		return this.fechaUmodif;
	}

	public void setFechaUmodif(Date fechaUmodif) {
		this.fechaUmodif = fechaUmodif;
	}

	public int getIdUsuarioUmodif() {
		return this.idUsuarioUmodif;
	}

	public void setIdUsuarioUmodif(int idUsuarioUmodif) {
		this.idUsuarioUmodif = idUsuarioUmodif;
	}

	public Coleccion getColeccion() {
		return coleccion;
	}

	public void setColeccion(Coleccion coleccion) {
		this.coleccion = coleccion;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Fuente getFuente() {
		return fuente;
	}

	public void setFuente(Fuente fuente) {
		this.fuente = fuente;
	}

	public Editorial getEditorial() {
		return editorial;
	}

	public void setEditorial(Editorial editorial) {
		this.editorial = editorial;
	}

	public String getPortadaUrl() {
		return portadaUrl;
	}

	public void setPortadaUrl(String portadaUrl) {
		this.portadaUrl = portadaUrl;
	}

	public String getUsuarioMail() {
		return usuarioMail;
	}

	public void setUsuarioMail(String usuarioMail) {
		this.usuarioMail = usuarioMail;
	}

	@Override
	public String toString() {
		return "Publicacion [id=" + id + ", descuento=" + descuento + ", estatus=" + estatus + ", isbn=" + isbn
				+ ", nombre=" + nombre + ", numeroPaginas=" + numeroPaginas + ", portada=" + Arrays.toString(portada)
				+ ", precio=" + precio + ", resumen=" + resumen + ", urlArchivo=" + urlArchivo + ", fechaUmodif="
				+ fechaUmodif + ", idUsuarioUmodif=" + idUsuarioUmodif + ", portadaUrl=" + portadaUrl + ", coleccion="
				+ coleccion + ", usuario=" + usuario + ", fuente=" + fuente + ", editorial=" + editorial + "]";
	}

	public Date getFechaCompraTemporal() {
		return fechaCompraTemporal;
	}

	public void setFechaCompraTemporal(Date fechaCompraTemporal) {
		this.fechaCompraTemporal = fechaCompraTemporal;
	}

	public boolean isComprada() {
		return comprada;
	}

	public void setComprada(boolean comprada) {
		this.comprada = comprada;
	}

}
